batch_size: 8
num_epochs: 20
learning_rate: 0.0001
sequence_length: 350
d_model: 512
dataset_name: opus_books
source_language: en
target_language: it
weights_folder: weights
model_filename_prefix: tmodel_
preload: latest
tokenizer_file_pattern: tokenizer_{0}.json
experiment_folder: runs/tmodel
